apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: print-date
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5  
  jobTemplate:
    spec:
      backoffLimit: 5  # the number to times kubernetes will try to run the container before marking the job as failed
      ttlSecondsAfterFinished: 100  # 
      template:
        spec:
          containers:
          - name: print-date
            image: node:14-alpine
            imagePullPolicy: IfNotPresent
            args:
            - -e
            - "console.log(new Date().toString());"
          restartPolicy: OnFailure
      parallelism: 1
      completions: 1
